baseURL = 'https://orangedigital.com.mx'  # Ajusta esto a tu dominio real
languageCode = 'es'
title = 'Orange Digital Blog'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "JSON"]

[params]
  description = "Blog de Orange Digital sobre desarrollo web y tecnolog√≠a"
  images = ["/images/og-image.jpg"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true 